version: "2"
prepare:
  fetch:
  - url: "https://raw.githubusercontent.com/uMotif/standards/master/codesniffer/phpcs.xml"
    path: "phpcs.xml"
  fetch:
  - url: "https://raw.githubusercontent.com/uMotif/standards/master/phpmd/phpmd.xml"
    path: "phpmd.xml"
checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    config:
      threshold: 7
  file-lines:
    config:
      threshold: 300
  method-complexity:
    config:
      threshold: 7
  method-count:
    config:
      threshold: 30
  method-lines:
    config:
      threshold: 100
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 5
plugins:
  phpcodesniffer:
    enabled: true
    config:
      ignore_warnings: true
      standard: "phpcs.xml"
  phpmd:
    enabled: true
    config:
      rulesets: "phpmd.xml"
  fixme:
    enabled: true
