version: "2"

checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    config:
      threshold: 7
  file-lines:
    config:
      threshold: 300
  method-complexity:
    config:
      threshold: 7
  method-count:
    config:
      threshold: 30
  method-lines:
    config:
      threshold: 100
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 5

plugins:
  phpcodesniffer:
    enabled: true
    config:
      ignore_warnings: true
      standard: "vendor/umotif/standards/codesniffer/phpcs.xml"
  phpmd:
    enabled: true
    config:
      rulesets: "vendor/umotif/standards/phpmd/phpmd.xml"
  fixme:
    enabled: true
